# config.toml for fsdproc CLI

# directory containing the data
# Required parameter
# data_direc must contain the folders `cloud`, `tci`, and a tiff file with the land outline (see `test/input`)
data_direc = "tests/input"

# whether to save figures (default: False)
save_figs = true

# directory to save figures
# Required parameter
save_direc = "temp"

# land mask to use
# Required parameter
land = "tests/input/reproj_land.tiff"

# Erosion parameters
## maximum number of iterations for erosion
erode_itmax = 8

## (inclusive) minimum number of iterations for erosion
erode_itmin = 3

step = -1

erosion_kernel_type = "diamond"

erosion_kernel_size = 1
